# Generated by Django 4.1.7 on 2023-03-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProjectAirtravel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveller',
            name='payment',
        ),
        migrations.AddField(
            model_name='traveller',
            name='amount',
            field=models.IntegerField(blank=True, default=1000, max_length=20),
        ),
        migrations.AddField(
            model_name='traveller',
            name='id_number',
            field=models.IntegerField(blank=True, default=1234523, max_length=20),
        ),
        migrations.AddField(
            model_name='traveller',
            name='seat',
            field=models.IntegerField(blank=True, default=1, max_length=20),
        ),
    ]
